export type OrbitModule = {
  slug: string;
  label: string;
  description: string;
  icon: string;
  group: "Website" | "Operations" | "Platform";
  singular: string;
  capabilities: string[];
};

/**
 * Page-based Orbit IA (WordPress / Webflow / Framer style).
 * Website group = one editor per public page — never nest all pages under Homepage.
 */
export const orbitModules: OrbitModule[] = [
  {
    slug: "homepage",
    label: "Homepage",
    singular: "section",
    icon: "layout-template",
    group: "Website",
    description: "Homepage sections only: Hero, About, previews, CTA.",
    capabilities: [
      "Hero",
      "About",
      "Rooms Preview",
      "Dining Preview",
      "Spa Preview",
      "Gallery Preview",
      "CTA",
    ],
  },
  {
    slug: "about",
    label: "About",
    singular: "about section",
    icon: "book-open",
    group: "Website",
    description: "Independent About page editor — cover, story, gallery and CTA.",
    capabilities: ["Cover", "Story", "Facilities", "Gallery", "Experience", "CTA", "SEO"],
  },
  {
    slug: "rooms",
    label: "Rooms",
    singular: "room",
    icon: "bed-double",
    group: "Website",
    description: "Professional room inventory editor with live pricing and occupancy.",
    capabilities: [
      "Cover & Gallery",
      "Occupancy",
      "Pricing",
      "Inventory",
      "SEO",
      "Publish",
    ],
  },
  {
    slug: "dining",
    label: "Dining",
    singular: "restaurant",
    icon: "utensils",
    group: "Website",
    description: "Dining page studio plus restaurant inventory.",
    capabilities: ["Hero", "Restaurants", "Gallery", "CTA", "SEO"],
  },
  {
    slug: "spa",
    label: "Spa",
    singular: "treatment",
    icon: "flower-2",
    group: "Website",
    description: "Spa page studio — treatments without published pricing.",
    capabilities: [
      "Hero Cover",
      "Treatments",
      "Wellness",
      "Features",
      "Hours",
      "FAQ",
      "Gallery",
      "CTA",
      "SEO",
    ],
  },
  {
    slug: "gallery",
    label: "Gallery",
    singular: "gallery item",
    icon: "images",
    group: "Website",
    description: "Gallery page studio and collections.",
    capabilities: ["Hero", "Collections", "CTA", "SEO"],
  },
  {
    slug: "offers",
    label: "Offers",
    singular: "offer",
    icon: "badge-percent",
    group: "Website",
    description: "Offers page studio and promotions.",
    capabilities: ["Hero", "Listing", "CTA", "SEO"],
  },
  {
    slug: "experiences",
    label: "Experiences",
    singular: "experience",
    icon: "compass",
    group: "Website",
    description: "Experiences page studio and experiences.",
    capabilities: ["Hero", "Listing", "CTA", "SEO"],
  },
  {
    slug: "wedding",
    label: "Wedding",
    singular: "wedding package",
    icon: "heart-handshake",
    group: "Website",
    description: "Wedding page studio and packages.",
    capabilities: ["Hero", "Packages", "Gallery", "CTA", "SEO"],
  },
  {
    slug: "meetings",
    label: "Meetings",
    singular: "meeting space",
    icon: "presentation",
    group: "Website",
    description: "Meetings page studio and spaces.",
    capabilities: ["Hero", "Spaces", "CTA", "SEO"],
  },
  {
    slug: "blog",
    label: "Blog",
    singular: "article",
    icon: "notebook-pen",
    group: "Website",
    description: "Full blogging system with drafts, SEO, media and scheduling.",
    capabilities: [
      "Posts",
      "Categories",
      "Tags",
      "Media",
      "SEO",
      "Drafts",
      "Publish",
      "Schedule",
    ],
  },
  {
    slug: "testimonials",
    label: "Testimonials",
    singular: "testimonial",
    icon: "quote",
    group: "Website",
    description: "Curated guest stories featured across the website.",
    capabilities: ["Guest details", "Quote", "Featured state"],
  },
  {
    slug: "contact",
    label: "Contact",
    singular: "contact page",
    icon: "messages-square",
    group: "Website",
    description:
      "Visual Contact page editor — cover, details, form, map and SEO.",
    capabilities: [
      "Cover Banner",
      "Contact Details",
      "Contact Form",
      "Google Map",
      "SEO",
    ],
  },
  {
    slug: "footer",
    label: "Footer",
    singular: "footer block",
    icon: "menu-square",
    group: "Website",
    description: "Global footer brand, links, contact and legal.",
    capabilities: ["Brand", "Links", "Contact", "Legal"],
  },
  {
    slug: "seo",
    label: "SEO",
    singular: "SEO record",
    icon: "search-check",
    group: "Website",
    description: "Page metadata, schema, social cards, robots and sitemap.",
    capabilities: ["Metadata", "OpenGraph", "Schema", "Robots", "Sitemap"],
  },
  {
    slug: "media-library",
    label: "Media Library",
    singular: "asset",
    icon: "folder-image",
    group: "Website",
    description: "Enterprise media manager with folders and hard delete.",
    capabilities: [
      "Folders",
      "Upload",
      "Replace",
      "Crop",
      "Bulk delete",
      "Trash",
    ],
  },
  {
    slug: "site-settings",
    label: "Settings",
    singular: "setting",
    icon: "settings-2",
    group: "Website",
    description:
      "Global brand, payment logos, contact, social, map and booking settings.",
    capabilities: [
      "Payment Methods",
      "Brand",
      "Contact",
      "Social",
      "WhatsApp",
      "Booking URL",
    ],
  },
  {
    slug: "reviews",
    label: "Reviews",
    singular: "review",
    icon: "star",
    group: "Operations",
    description: "Moderate verified guest reviews and ratings.",
    capabilities: ["Moderation", "Rating", "Feature", "Publish"],
  },
  {
    slug: "newsletter",
    label: "Newsletter",
    singular: "subscriber",
    icon: "mail-plus",
    group: "Operations",
    description: "Search, export and manage newsletter subscribers.",
    capabilities: ["Search", "CSV export", "Delete"],
  },
  {
    slug: "bookings",
    label: "Bookings",
    singular: "booking",
    icon: "calendar-check",
    group: "Operations",
    description: "Upcoming, confirmed, cancelled and completed stays.",
    capabilities: ["Status", "Guests", "Payment", "CSV export"],
  },
  {
    slug: "contact-messages",
    label: "Contact Messages",
    singular: "message",
    icon: "messages-square",
    group: "Operations",
    description: "Read, reply, archive and manage guest enquiries.",
    capabilities: ["Inbox", "Reply", "Archive", "Delete"],
  },
  {
    slug: "menus",
    label: "Menus",
    singular: "menu",
    icon: "menu-square",
    group: "Platform",
    description: "Header, footer and contextual navigation management.",
    capabilities: ["Navigation trees", "Ordering", "Visibility"],
  },
  {
    slug: "users",
    label: "Users",
    singular: "user",
    icon: "users-round",
    group: "Platform",
    description: "Administrator accounts, roles and access state.",
    capabilities: ["Accounts", "Roles", "Deactivate"],
  },
  {
    slug: "security",
    label: "Security",
    singular: "security event",
    icon: "shield-check",
    group: "Platform",
    description: "Sessions, login activity, lockouts and security posture.",
    capabilities: ["Sessions", "Failed logins", "Revoke"],
  },
  {
    slug: "backup",
    label: "Backup",
    singular: "backup",
    icon: "database-backup",
    group: "Platform",
    description: "Track database and media backup operations.",
    capabilities: ["Database backup", "Media manifest", "History"],
  },
  {
    slug: "system-logs",
    label: "System Logs",
    singular: "audit event",
    icon: "scroll-text",
    group: "Platform",
    description: "Immutable administrative activity and operational logs.",
    capabilities: ["Audit trail", "Filter", "Export"],
  },
];

export const moduleBySlug = new Map(
  orbitModules.map((module) => [module.slug, module])
);

/** Public path for each Website page studio. */
export const PAGE_PUBLIC_PATH: Record<string, string> = {
  homepage: "/",
  about: "/about",
  rooms: "/rooms",
  dining: "/dining",
  spa: "/spa",
  gallery: "/gallery",
  offers: "/offers",
  experiences: "/experiences",
  wedding: "/wedding",
  meetings: "/meetings",
  blog: "/blog",
  testimonials: "/",
  contact: "/contact",
  footer: "/",
  seo: "/",
  "media-library": "/orbit/media-library",
  "site-settings": "/",
};
