-- AlterTable
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "airportPickup" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "pickupVehicles" INTEGER;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "pickupAmount" DECIMAL(12,2);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "flightNumber" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "pickupDate" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "pickupTime" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "pickupNotes" TEXT;
